# Lab-1-NumPy Exercises 
**Padmaja - 19BAI1107**

#### Import NumPy 

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
a1=np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [10]:
a2=np.ones(10)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 6 twelves

In [11]:
a3=6*np.ones(12)
a3

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

#### Create an array of the integers from 50 to 75

In [12]:
a4=np.arange(50,76)
a4

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75])

#### Create an array of all the odd integers from 50 to 75

In [13]:
a5=np.arange(51,76,2)
a5

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75])

#### Create a 3x4 matrix with values ranging from 0 to 12

In [17]:
m1=np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Create a 5x5 identity matrix

In [14]:
m2=np.eye(5)
m2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [15]:
np.random.rand(1)

array([0.62077588])

# Use NumPy to generate an array of 10 random numbers sampled from a standard normal distribution

In [19]:
a6=np.random.randn(10)
a6

array([ 0.32970306, -1.2630724 , -0.15223526, -0.04512215,  0.29266078,
        1.44439894,  2.13900166, -0.48409347,  0.44096394,  1.45576507])

#### Create the following matrix:

In [20]:
m3=np.arange(1,101).reshape(10,10)
m3

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Create the following matrix:

In [21]:
m4=np.arange(10,1001,10).reshape(10,10)
m4

array([[  10,   20,   30,   40,   50,   60,   70,   80,   90,  100],
       [ 110,  120,  130,  140,  150,  160,  170,  180,  190,  200],
       [ 210,  220,  230,  240,  250,  260,  270,  280,  290,  300],
       [ 310,  320,  330,  340,  350,  360,  370,  380,  390,  400],
       [ 410,  420,  430,  440,  450,  460,  470,  480,  490,  500],
       [ 510,  520,  530,  540,  550,  560,  570,  580,  590,  600],
       [ 610,  620,  630,  640,  650,  660,  670,  680,  690,  700],
       [ 710,  720,  730,  740,  750,  760,  770,  780,  790,  800],
       [ 810,  820,  830,  840,  850,  860,  870,  880,  890,  900],
       [ 910,  920,  930,  940,  950,  960,  970,  980,  990, 1000]])

# Create an array of 25 linearly spaced points between 0 and 1:

In [22]:
a7=np.linspace(0,1,25)
a7

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

## Numpy Indexing and Selection

You are given the below matrix and find the resultant matrix by answering the questions

In [3]:
m5=np.arange(51,76).reshape(5,5)# Write the code to get the below matrix
m5

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75]])

In [26]:
m5[2:,1:]# Write the code to get the below matrix from the above 5x5 matrix

array([[62, 63, 64, 65],
       [67, 68, 69, 70],
       [72, 73, 74, 75]])

In [4]:
m5[3,4]# Write the code to get the below matrix from the above 5x5 matrix  

70

In [41]:
m5[0:3,1:2]# Write the code to get the output as shown below

array([[52],
       [57],
       [62]])

In [32]:
m5[4,:]# Write the code to get the output as shown below

array([71, 72, 73, 74, 75])

In [33]:
m5[3:,:]# Write the code to get the output as shown below

array([[66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75]])

### Perform the following operations

#### Get the sum of all the values in the  matrix

In [35]:
np.sum(m5)

1575

#### Get the standard deviation of the values in matrix

In [36]:
np.std(m5)

7.211102550927978

#### Get the sum of all the columns in matrix

In [37]:
np.sum(m5,axis=0)

array([305, 310, 315, 320, 325])

#### Get the sum of all the rows in matrix

In [38]:
np.sum(m5,axis=1)

array([265, 290, 315, 340, 365])