# V Padmaja - 19BAI1107
## b) Lab 7 - MULTILAYER PERCEPTRON

In [18]:
import numpy as np
import pandas as pd
from pandas import DataFrame
from sklearn.preprocessing import MinMaxScaler,MaxAbsScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
%matplotlib inline

**IMPORTING DATA**

In [35]:
df=pd.read_excel('Multiclass-dataset.xlsx')
df.head()

P1    P2    P3    P4    P5    P6    P7    P8   P9   P10  ...   P12  \
0  3.30  7.44  1.52  3.27  0.07  2.14  0.75  0.66  0.0  54.8  ...  50.7   
1  3.43  7.63  1.63  3.27  0.05  2.01  0.74  0.65  0.0  51.8  ...  47.9   
2  3.41  7.32  1.52  3.18  0.07  2.09  0.80  0.70  0.0  54.0  ...  54.4   
3  3.78  7.85  1.69  3.35  0.03  1.98  0.77  0.67  0.0  57.7  ...  48.9   
4  3.90  7.99  1.61  3.43  0.02  2.14  0.77  0.71  0.0  59.1  ...  54.1   

     P13   P14   P15   P16   P17   P18  P19  P20  Target Label  
0   6.55  4.09  4.26  0.01  0.00  24.7  2.7  1.6            V1  
1   8.35  5.08  5.01  0.01  0.00  23.3  2.3  1.8            V1  
2   9.27  6.85  7.14  0.19  0.06  25.0  2.5 -0.9            V1  
3  10.26  5.96  5.47  0.05  0.01  24.1  5.6  2.1            V1  
4   8.19  5.81  4.72  0.64  0.16  26.8  2.5  2.1            V1  

[5 rows x 21 columns]

In [36]:
dict_diff={
    'V1':1,
    'V2':2,
    'V3':3,
    'V4':4,
    'V5':5,
    'V6':6,
    'V7':7,
    'V8':8,
    'V9':9,
    'V10':10
    }

In [37]:
df['re']=df['Target Label'].apply(lambda x:dict_diff[x])

In [38]:
df['re'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [39]:
df.shape

(400, 22)

In [40]:
df.describe(include='all')

P1          P2          P3         P4          P5          P6  \
count   400.000000  400.000000  400.000000  400.00000  400.000000  400.000000   
unique         NaN         NaN         NaN        NaN         NaN         NaN   
top            NaN         NaN         NaN        NaN         NaN         NaN   
freq           NaN         NaN         NaN        NaN         NaN         NaN   
mean      3.441575    7.403225    1.595625    3.12340    0.056550    1.970525   
std       0.395690    0.421662    0.140773    0.19666    0.015188    0.196999   
min       2.410000    6.280000    1.180000    2.60000    0.020000    1.220000   
25%       3.167500    7.100000    1.520000    3.00000    0.040000    1.870000   
50%       3.435000    7.420000    1.610000    3.10000    0.060000    1.980000   
75%       3.710000    7.710000    1.690000    3.27000    0.070000    2.090000   
max       4.720000    8.630000    2.210000    3.69000    0.130000    2.690000   

                P7          P8          P9        P10  ...         P13  \
count   400.000000  400.000000  400.000000  400.00000  ...  400.000000   
unique         NaN         NaN         NaN        NaN  ...         NaN   
top            NaN         NaN         NaN        NaN  ...         NaN   
freq           NaN         NaN         NaN        NaN  ...         NaN   
mean      0.787700    0.690450    0.020500  103.88375  ...   13.666600   
std       0.027931    0.017652    0.092878   40.77963  ...    3.934187   
min       0.670000    0.640000    0.000000   43.30000  ...    5.700000   
25%       0.770000    0.680000    0.000000   75.35000  ...   10.930000   
50%       0.790000    0.690000    0.000000   95.00000  ...   13.535000   
75%       0.810000    0.700000    0.000000  119.92500  ...   15.922500   
max       0.870000    0.760000    0.600000  183.20000  ...   31.000000   

               P14        P15         P16         P17         P18         P19  \
count   400.000000  400.00000  400.000000  400.000000  400.000000  400.000000   
unique         NaN        NaN         NaN         NaN         NaN         NaN   
top            NaN        NaN         NaN         NaN         NaN         NaN   
freq           NaN        NaN         NaN         NaN         NaN         NaN   
mean     10.190050    8.39965    0.528475    0.155375   39.988250   10.069250   
std       3.384236    3.35507    1.017907    0.301290   16.699209    5.942395   
min       4.070000    3.49000    0.000000    0.000000   20.200000    0.100000   
25%       7.607500    6.01750    0.000000    0.000000   28.875000    3.875000   
50%       9.840000    7.34500    0.010000    0.000000   33.500000   11.250000   
75%      12.415000    9.82500    0.270000    0.072500   41.725000   15.325000   
max      22.180000   21.88000    3.730000    0.990000   76.300000   21.800000   

               P20  Target Label          re  
count   400.000000           400  400.000000  
unique         NaN            10         NaN  
top            NaN            V3         NaN  
freq           NaN            40         NaN  
mean     10.600000           NaN    5.500000  
std       6.213398           NaN    2.875878  
min      -0.900000           NaN    1.000000  
25%       6.400000           NaN    3.000000  
50%      10.900000           NaN    5.500000  
75%      14.325000           NaN    8.000000  
max      28.600000           NaN   10.000000  

[11 rows x 22 columns]

In [41]:
x=df[['P1','P2','P3','P4','P5','P6','P7','P8','P9','P10','P11','P12','P13','P14','P15','P16','P17','P18','P19','P20']]
y=df['re']
x.head(2)

P1    P2    P3    P4    P5    P6    P7    P8   P9   P10   P11   P12  \
0  3.30  7.44  1.52  3.27  0.07  2.14  0.75  0.66  0.0  54.8  49.7  50.7   
1  3.43  7.63  1.63  3.27  0.05  2.01  0.74  0.65  0.0  51.8  47.3  47.9   

    P13   P14   P15   P16  P17   P18  P19  P20  
0  6.55  4.09  4.26  0.01  0.0  24.7  2.7  1.6  
1  8.35  5.08  5.01  0.01  0.0  23.3  2.3  1.8

In [42]:
y.head(2)

0    1
1    1
Name: re, dtype: int64

**Splitting into Training and testing**

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)
x_train.shape

(240, 20)

In [44]:
y_train.shape

(240,)

**Training Model using MLP Classifier**

In [45]:
from sklearn.neural_network import MLPClassifier

In [46]:
mlp=MLPClassifier(max_iter=500,activation='relu')
mlp

MLPClassifier(max_iter=500)

In [47]:
mlp.fit(x_train,y_train)

MLPClassifier(max_iter=500)

**Testing**

In [48]:
prediction=mlp.predict(x_test)
prediction

array([ 1, 10, 10,  7, 10,  1,  7,  1, 10,  9,  3,  3,  6,  9,  1,  4,  5,
        6,  2, 10, 10,  3,  4,  9,  5,  4,  5,  1,  9,  8,  3, 10,  8,  1,
        6,  8,  7, 10,  2,  4,  1,  5,  6,  3,  2, 10, 10,  4,  3,  9, 10,
        5,  7, 10,  3,  1,  9,  8,  1,  3,  3, 10,  7,  8,  4,  7,  9,  1,
        5,  7,  7, 10, 10,  6,  3,  8,  7,  8,  3, 10,  6, 10,  3,  7,  6,
        4,  1,  9, 10,  1,  7,  5,  9,  6,  4,  9,  5,  4,  4,  3,  4,  6,
        3,  9,  4, 10,  6,  9,  7,  3,  3, 10, 10, 10,  8,  8,  6,  4,  8,
       10,  3,  1, 10,  8,  5,  6, 10,  4,  5,  2,  3,  1,  6,  7,  4,  4,
        8,  7, 10,  8,  2,  4,  5,  8,  4,  6,  5,  5,  1,  5,  6,  6,  8,
        5, 10,  7,  9, 10,  7,  3], dtype=int64)

**Model Evaluation**

In [49]:
confusion_matrix(y_test,prediction)

array([[13,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0, 13],
       [ 2,  0, 11,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2, 11,  1,  0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  6,  5,  0,  0,  3,  0],
       [ 0,  0,  2,  2,  4,  9,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  2, 13,  0,  0],
       [ 0,  0,  0,  4,  4,  2,  0,  0,  7,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0, 15]], dtype=int64)

In [50]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           1       0.87      0.76      0.81        17
           2       0.80      0.24      0.36        17
           3       0.58      0.79      0.67        14
           4       0.61      0.65      0.63        17
           5       0.40      0.43      0.41        14
           6       0.56      0.53      0.55        17
           7       0.88      0.88      0.88        16
           8       0.87      0.87      0.87        15
           9       0.54      0.41      0.47        17
          10       0.54      0.94      0.68        16

    accuracy                           0.64       160
   macro avg       0.66      0.65      0.63       160
weighted avg       0.67      0.64      0.63       160



**Model Accuracy is 64%**
